Feature/maw1 32 navigation with framework
CPNV-ES/oopers-maw-exercise-looper pull request #6
Opened 2023-11-01 08:41 UTC by EliottJaquierEdu

2023-11-01 10:16 UTC, drutz-cpnv requested changes

2023-11-01 10:16 UTC, drutz-cpnv commented on views/exercises/answering/fulfillment.php
> +include $_SERVER['DOCUMENT_ROOT'] . "/../views/headers/heading-answering.php" ?>
You MUST NOT use `require` nor `include` instead use View concatenate

2023-11-01 10:16 UTC, drutz-cpnv commented on views/exercises/answering/fulfillment.php
> +    <form action="/exercises/7/fulfillments" accept-charset="UTF-8" method="post">
You can already use `url` method in your views to generate your urls

2023-11-01 10:16 UTC, drutz-cpnv commented on views/templates/base.php
> +<?= $content ?>
You will have to change `$content` to `$this->body`

2023-11-10 09:34 UTC, EliottJaquierEdu commented
All resolved, feel free to re-review or merge!

2023-11-12 14:03 UTC, merged